- alias: Goes away
  trigger:
  - platform: zone
    entity_id: person.ross_sutherland
    zone: zone.home
    event: leave
  action:
  - service: climate.set_preset_mode
    target:
      entity_id: climate.boiler
    data:
      preset_mode: away

- alias: Returns home
  trigger:
  - platform: zone
    entity_id: person.ross_sutherland
    zone: zone.home
    event: enter
  action:
  - service: climate.set_preset_mode
    target:
      entity_id: climate.boiler
    data:
      preset_mode: none